import {
  ADD_DEPENDENTS,
  DELETE_DEPENDENT,
  GET_DEPENDENTS,
  UPDATE_DEPENDENTS,
} from 'dashboard-app/queries/dependents';
import {
  ADD_DISABILITY,
  DELETE_DISABILITY,
  GET_DISABILITY,
  UPDATE_DISABILITY,
} from 'dashboard-app/queries/disabilities';
import {
  ADD_FAMILY_HISTORY,
  DELETE_FAMILY_HISTORY,
  GET_FAMILY_HISTORIES,
  UPDATE_FAMILY_HISTORY,
} from 'dashboard-app/queries/familyHistories';
import {
  ADD_GYNECOLOGIC_HISTORY,
  DELETE_GYNECOLOGIC_HISTORY,
  GET_GYNECOLOGIC_HISTORIES,
  UPDATE_GYNECOLOGIC_HISTORY,
} from 'dashboard-app/queries/gynecologicHistories';
import { DELETE_MY_HMO, GET_HMOS, SAVE_HMO, UPDATE_HMO } from 'dashboard-app/queries/hmos';
import {
  ADD_NEXT_OF_KIN,
  DELETE_NEXT_OF_KIN,
  GET_NEXT_OF_KIN,
  UPDATE_NEXT_OF_KIN,
} from 'dashboard-app/queries/nextOfKin';
import {
  ADD_OBSTETRIC_HISTORY,
  DELETE_OBSTETRIC_HISTORY,
  GET_OBSTETRICS,
  UPDATE_OBSTETRIC_HISTORY,
} from 'dashboard-app/queries/obstetricHistories';
import {
  ADD_ENCOUNTER,
  DELETE_ENCOUNTER,
  GET_ENCOUNTERS,
  UPDATE_ENCOUNTER,
} from 'dashboard-app/queries/pastEncounters';
import {
  ADD_PAST_SURGERY,
  DELETE_PAST_SURGERY,
  GET_PAST_SURGERY,
  UPDATE_PAST_SURGERY,
} from 'dashboard-app/queries/pastSurgeries';
import {
  ADD_PHYSICAL_ACTIVITY,
  DELETE_PHYSICAL_ACTIVITY,
  GET_PHYSICAL_ACTIVITIES,
  UPDATE_PHYSICAL_ACTIVITY,
} from 'dashboard-app/queries/physicalActivities';
import {
  ADD_PRE_EXISTING_CONDITION,
  DELETE_PRE_EXISTING_CONDITION,
  GET_PRE_EXISTING_CONDITION,
  UPDATE_PRE_EXISTING_CONDITION,
} from 'dashboard-app/queries/preExistingConditions';
import {
  ADD_SOCIAL_HABIT,
  DELETE_SOCIAL_HABIT,
  GET_SOCIAL_HABIT,
  UPDATE_SOCIAL_HABIT,
} from 'dashboard-app/queries/socialHabits';
import { Gender } from 'graphql-types/globalTypes';
import { nanoid } from 'nanoid';

const profileSectionParams = {
  Dependents: {
    fetchPath: 'getDependents',
    addPath: 'addDependentInfo',
    updatePath: 'updateDependentInfo',
    deletePath: 'deleteDependentInfo',
    fetchQuery: GET_DEPENDENTS,
    addQuery: ADD_DEPENDENTS,
    deleteQuery: DELETE_DEPENDENT,
    updateQuery: UPDATE_DEPENDENTS,
    initialValues: {
      firstName: '',
      lastName: '',
      dateOfBirth: null,
      relationship: '',
      gender: null,
      bloodGroup: '',
    },
  },
  'Pre-existing Condition': {
    fetchPath: 'getPreExistingConditions',
    addPath: 'addPreExistingConditionInfo',
    updatePath: 'updatePreExistingConditionInfo',
    deletePath: 'deletePreExistingConditionInfo',
    fetchQuery: GET_PRE_EXISTING_CONDITION,
    addQuery: ADD_PRE_EXISTING_CONDITION,
    updateQuery: UPDATE_PRE_EXISTING_CONDITION,
    deleteQuery: DELETE_PRE_EXISTING_CONDITION,
    initialValues: {
      id: nanoid(10),
      condition: '',
      diagnosedDate: null,
      duration: null,
      additionalNote: '',
    },
  },
  'Social History': {
    fetchPath: 'getHabits',
    addPath: 'addHabitInfo',
    updatePath: 'updateHabitInfo',
    deletePath: 'deleteHabitInfo',
    fetchQuery: GET_SOCIAL_HABIT,
    addQuery: ADD_SOCIAL_HABIT,
    updateQuery: UPDATE_SOCIAL_HABIT,
    deleteQuery: DELETE_SOCIAL_HABIT,
    initialValues: {
      id: nanoid(10),
      socialHabit: '',
      level: '',
      duration: null,
      additionalNote: '',
    },
  },
  'Physical Activity': {
    fetchPath: 'getPhysicalActivities',
    addPath: 'addPhysicalActivityInfo',
    updatePath: 'updatePhysicalActivityInfo',
    deletePath: 'deletePhysicalActivityInfo',
    fetchQuery: GET_PHYSICAL_ACTIVITIES,
    addQuery: ADD_PHYSICAL_ACTIVITY,
    updateQuery: UPDATE_PHYSICAL_ACTIVITY,
    deleteQuery: DELETE_PHYSICAL_ACTIVITY,
    initialValues: {
      id: nanoid(10),
      type: 'Aerobic/Endurance',
      name: '',
      additionalNote: '',
    },
  },
  Disability: {
    fetchPath: 'getDisabilities',
    addPath: 'addDisabilityInfo',
    updatePath: 'updateDisabilityInfo',
    deletePath: 'deleteDisabilityInfo',
    fetchQuery: GET_DISABILITY,
    addQuery: ADD_DISABILITY,
    updateQuery: UPDATE_DISABILITY,
    deleteQuery: DELETE_DISABILITY,
    initialValues: {
      id: nanoid(10),
      type: '',
      disability: 'Hearing Impairment',
      additionalNote: '',
    },
  },
  'Family History': {
    fetchPath: 'getFamilyHistories',
    addPath: 'addFamilyHistoryInfo',
    updatePath: 'updateFamilyHistoryInfo',
    deletePath: 'deleteFamilyHistoryInfo',
    fetchQuery: GET_FAMILY_HISTORIES,
    addQuery: ADD_FAMILY_HISTORY,
    updateQuery: UPDATE_FAMILY_HISTORY,
    deleteQuery: DELETE_FAMILY_HISTORY,
    initialValues: {
      id: nanoid(10),
      firstName: '',
      middleName: '',
      lastName: '',
      relationship: '',
      condition: [],
      additionalNote: '',
    },
  },
  'Past Surgical History': {
    fetchPath: 'getPastSurgeries',
    addPath: 'addPastSurgeryInfo',
    updatePath: 'updatePastSurgeryInfo',
    deletePath: 'deletePastSurgeryInfo',
    fetchQuery: GET_PAST_SURGERY,
    addQuery: ADD_PAST_SURGERY,
    updateQuery: UPDATE_PAST_SURGERY,
    deleteQuery: DELETE_PAST_SURGERY,
    initialValues: {
      id: nanoid(10),
      type: '',
      operationDate: null,
      additionalNote: '',
    },
  },
  'Obstetric History': {
    fetchPath: 'getObstetricHistories',
    addPath: 'addObstetricInfo',
    updatePath: 'updateObstetricHistoryInfo',
    deletePath: 'deleteObstetricInfo',
    fetchQuery: GET_OBSTETRICS,
    addQuery: ADD_OBSTETRIC_HISTORY,
    updateQuery: UPDATE_OBSTETRIC_HISTORY,
    deleteQuery: DELETE_OBSTETRIC_HISTORY,
    initialValues: {
      id: nanoid(10),
      lastBirth: null,
      childrenCount: '',
      additionalNote: '',
    },
  },
  'Gynecologic History': {
    fetchPath: 'getGynecologicHistories',
    addPath: 'addGynecologicHistoryInfo',
    updatePath: 'updateGynecologicHistoryInfo',
    deletePath: 'deleteGynecologicInfo',
    fetchQuery: GET_GYNECOLOGIC_HISTORIES,
    addQuery: ADD_GYNECOLOGIC_HISTORY,
    updateQuery: UPDATE_GYNECOLOGIC_HISTORY,
    deleteQuery: DELETE_GYNECOLOGIC_HISTORY,
    initialValues: {
      id: nanoid(10),
      firstMenstrualAge: null,
      menstrualCycleLength: null,
      menstrualFlowDuration: null,
      lastMenstrualPeriod: null,
      menstrualFlow: '',
      contraceptiveUse: '',
      contraceptiveType: '',
      miscarriageOrAbortion: '',
      miscarriageOrAbortionCount: 0,
      additionalNote: '',
    },
  },
  'Past Encounters': {
    fetchPath: 'getPastEncounters',
    addPath: 'addPastEncounterInfo',
    updatePath: 'updatePastEncounterInfo',
    deletePath: 'deletePastEncounterInfo',
    fetchQuery: GET_ENCOUNTERS,
    addQuery: ADD_ENCOUNTER,
    updateQuery: UPDATE_ENCOUNTER,
    deleteQuery: DELETE_ENCOUNTER,
    initialValues: {
      id: nanoid(10),
      details: [
        {
          id: nanoid(10),
          diagnosisDate: null,
          duration: null,
          diagnosis: '',
          diagnosedBy: '',
          specialty: '',
          symptoms: [],
        },
      ],
      clinicName: '',
      clinicAddress: '',
      additionalNote: '',
    },
  },
  'Next of Kin': {
    fetchPath: 'getNextOfKins',
    addPath: 'addNextOfKinInfo',
    updatePath: 'updateNextOfKinInfo',
    deletePath: 'deleteNextOfKinInfo',
    fetchQuery: GET_NEXT_OF_KIN,
    addQuery: ADD_NEXT_OF_KIN,
    updateQuery: UPDATE_NEXT_OF_KIN,
    deleteQuery: DELETE_NEXT_OF_KIN,
    initialValues: {
      id: nanoid(10),
      firstName: '',
      lastName: '',
      email: '',
      gender: Gender.Male,
      genoType: '',
      phoneNumber: {
        countryName: 'Nigeria',
        countryCode: '+234',
        value: '',
      },
      phoneNumberAlt: {
        countryName: 'Nigeria',
        countryCode: '+234',
        value: '',
      },
      relationship: '',
      occupation: '',
      address: '',
    },
  },
  'Coverage Information': {
    fetchPath: 'fetchHmos',
    updatePath: 'updateMyHmos',
    addPath: 'saveMyHmos',
    deletePath: 'deleteMyHmo',
    fetchQuery: GET_HMOS,
    updateQuery: UPDATE_HMO,
    addQuery: SAVE_HMO,
    deleteQuery: DELETE_MY_HMO,
    initialValues: {
      id: nanoid(10),
      memberNumber: '',
      memberPlan: '',
      hmoProvider: '',
      memberStartDate: null,
      memberStatus: '',
      companyName: '',
      companyAddress: '',
      primaryProviderName: '',
      secondaryProviderName: '',
      tertiaryProviderName: '',
      primaryProviderAddress: '',
      secondaryProviderAddress: '',
      tertiaryProviderAddress: '',
    },
  },
};

export const PROFILE_INFOS_FILTER_OPTIONS = {
  skip: 0,
  take: 50,
};

export default profileSectionParams;
